services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: flowchart_db
      POSTGRES_USER: flowchart_user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
